#!/bin/sh
#
# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

SYSTEM_PROPERTIES="-Dserver.port=${SERVER_PORT}"
SYSTEM_PROPERTIES+=" -Dlogging.config=${LOGGING_CONFIG}"
SYSTEM_PROPERTIES+=" -Dapplication.version=${APPLICATION_VERSION}"
SYSTEM_PROPERTIES+=" -Dthread.pool.size=${THREAD_POOL_SIZE}"

EPID_PROPERTIES="-Dorg.sdo.epid.epid-online-url=${ORG_SDO_EPID_EPID_ONLINE_URL}"
EPID_PROPERTIES+=" -Dorg.sdo.epid.test-mode=${ORG_SDO_EPID_TEST_MODE}"

ONDIE_ECDSA_PROPERTIES="-Dorg.sdo.ops.ondie-ecdsa-material-path=${ORG_SDO_OPS_ONDIE_ECDSA_MATERIAL_PATH}"
ONDIE_ECDSA_PROPERTIES+=" -Dorg.sdo.ops.ondie-ecdsa-material-urls=${ORG_SDO_OPS_ONDIE_ECDSA_MATERIAL_URLS}"
ONDIE_ECDSA_PROPERTIES+=" -Dorg.sdo.ops.ondie-ecdsa-material-update=${ORG_SDO_OPS_ONDIE_ECDSA_MATERIAL_UPDATE}"

OCS_ENDPOINT_PROPERTIES="-Drest.api.server=${REST_API_SERVER}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.device.state.path=${REST_API_DEVICE_STATE_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.voucher.path=${REST_API_VOUCHER_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.serviceinfo.path=${REST_API_SERVICEINFO_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.serviceinfo.value.path=${REST_API_SERVICEINFO_VALUE_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.psi.path=${REST_API_PSI_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.error.path=${REST_API_ERROR_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.setupinfo.path=${REST_API_SETUPINFO_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.signature.path=${REST_API_SIGNATURE_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.ciphers.path=${REST_API_CIPHERS_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.session.path=${REST_API_SESSION_PATH}"
OCS_ENDPOINT_PROPERTIES+=" -Drest.api.owner.resale.support.path=${REST_API_OWNER_RESALE_SUPPORT_PATH}"

CLIENT_TLS_PROPERTIES="-Dclient.ssl.key-store-type=${CLIENT_SSL_KEYSTORE_TYPE}"
CLIENT_TLS_PROPERTIES+=" -Dclient.ssl.trust-store-type=${CLIENT_SSL_TRUSTSTORE_TYPE}"
CLIENT_TLS_PROPERTIES+=" -Dclient.ssl.key-store=${CLIENT_SSL_KEYSTORE}"
CLIENT_TLS_PROPERTIES+=" -Dclient.ssl.trust-store=${CLIENT_SSL_TRUSTSTORE}"
CLIENT_TLS_PROPERTIES+=" -Dclient.ssl.key-store-password=${CLIENT_SSL_KEYSTORE_PASSWORD}"
CLIENT_TLS_PROPERTIES+=" -Dclient.ssl.trust-store-password=${CLIENT_SSL_TRUSTSTORE_PASSWORD}"

# The pattern to find the binary executable file
bin_file=ops*.war

# Base-directory where all binaries are found. This should be the base of the
# folder to which binary package is extracted.
base_dir=$(realpath ../..)

# Find the absolute path of executable file.
bin_path=$(find $base_dir -name $bin_file)

# Run the executable file
if [ -z "$bin_path" ]; then
  echo "Couldn't find binary file. Please recheck binary package"
else
  exec java ${SYSTEM_PROPERTIES} ${EPID_PROPERTIES} ${ONDIE_ECDSA_PROPERTIES} ${OCS_ENDPOINT_PROPERTIES} ${CLIENT_TLS_PROPERTIES} -jar -Djava.library.path=$base_dir/sdo $bin_path
fi
