#!/bin/sh
#
# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

SYSTEM_PROPERTIES="-Dserver.port=${SERVER_PORT}"
SYSTEM_PROPERTIES+=" -Dlogging.config=${LOGGING_CONFIG}"
SYSTEM_PROPERTIES+=" -Dapplication.version=${APPLICATION_VERSION}"

FILE_SYSTEM_PROPERTIES="-Dfs.root.dir=${FS_ROOT_DIR} -Dfs.owner.keystore=${FS_OWNER_KEYSTORE}"
FILE_SYSTEM_PROPERTIES+=" -Dfs.owner.keystore-password=${FS_OWNER_KEYSTORE_PASSWORD}"
FILE_SYSTEM_PROPERTIES+=" -Dfs.devices.dir=${FS_DEVICES_DIR} -Dfs.values.dir=${FS_VALUES_DIR}"

TO_PROPERTIES="-Dto0.rest.api=${TO0_REST_API}"
TO_PROPERTIES+=" -Dto0.waitseconds=${TO0_WAITSECONDS}"
TO_PROPERTIES+=" -Dto0.scheduler.interval=${TO0_SCHEDULER_INTERVAL}"
TO_PROPERTIES+=" -Dto2.credential-reuse.enabled=${TO2_CREDENTIAL_REUSE_ENABLED}"
TO_PROPERTIES+=" -Dto2.owner-resale.enabled=${TO2_OWNER_RESALE_ENABLED}"

JAVA_SPRING_TLS_PROPERTIES="-Dserver.ssl.key-store-type=${SERVER_SSL_KEYSTORE_TYPE}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.trust-store-type=${SERVER_SSL_TRUSTSTORE_TYPE}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.key-store=${SERVER_SSL_KEYSTORE}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.trust-store=${SERVER_SSL_TRUSTSTORE}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.key-store-password=${SERVER_SSL_KEYSTORE_PASSWORD}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.trust-store-password=${SERVER_SSL_TRUSTSTORE_PASSWORD}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.client-auth=${SERVER_SSL_CLIENT_AUTH}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.ciphers=${SERVER_SSL_CIPHERS}"
JAVA_SPRING_TLS_PROPERTIES+=" -Dserver.ssl.enabled-protocols=${SERVER_SSL_ENABLED_PROTOCOLS}"

# The pattern to find the binary executable file
bin_file=ocsfs*.war

# Base-directory where all binaries are found. This should be the base of the
# folder to which binary package is extracted.
base_dir=$(realpath ../..)

# Find the absolute path of executable file.
bin_path=$(find $base_dir -name $bin_file)

# Run the executable file
if [ -z "$bin_path" ]; then
  echo "Couldn't find binary file. Please recheck binary package"
else
  exec java ${SYSTEM_PROPERTIES} ${FILE_SYSTEM_PROPERTIES} ${TO_PROPERTIES} ${JAVA_SPRING_TLS_PROPERTIES} -jar -Djava.library.path=$base_dir/sdo $bin_path
fi
